services:
 # Sql Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

  # Identity Api
  identity.api:
    image: ${DOCKER_REGISTRY-}identity.api
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.Api/Dockerfile

networks:
  ums_network:
    driver: bridge

volumes:
  sqlserver-data: