// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Student.Api.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Student.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20260703170122_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Student.Api.Domain.Admission.AdmissionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ApplicantContactInfo", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantContactInfo#ApplicantContactInfo", b1 =>
                        {
                            b1.Property<bool>("HasApplicantContactInfo")
                                .HasColumnType("boolean");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantContactInfo#ApplicantContactInfo.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("AdditionalInfo")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("Address_AdditionalInfo");

                                    b2.Property<string>("BuildingNumber")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("Address_BuildingNumber");

                                    b2.Property<string>("City")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Address_City");

                                    b2.Property<string>("Province")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Address_Province");

                                    b2.Property<string>("Street")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("Address_Street");

                                    b2.Property<string>("Unit")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("Address_Unit");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PostalCode", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantContactInfo#ApplicantContactInfo.Address#Address.PostalCode#PostalCode", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("Value")
                                                .HasMaxLength(10)
                                                .HasColumnType("character varying(10)")
                                                .HasColumnName("Address_PostalCode");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantContactInfo#ApplicantContactInfo.Email#Email", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("Email");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Mobile", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantContactInfo#ApplicantContactInfo.Mobile#MobileNumber", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(11)
                                        .HasColumnType("character varying(11)")
                                        .HasColumnName("Mobile");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Phone", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantContactInfo#ApplicantContactInfo.Phone#PhoneNumber", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("Phone");
                                });

                            b1.HasDiscriminator<bool>("HasApplicantContactInfo").HasValue(true);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ApplicantPersonalInfo", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantPersonalInfo#ApplicantPersonalInfo", b1 =>
                        {
                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("BirthPlace")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("Gender")
                                .HasColumnType("integer");

                            b1.Property<bool>("HasApplicantPersonalInfo")
                                .HasColumnType("boolean");

                            b1.Property<string>("IssuePlace")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("MaritalStatus")
                                .HasColumnType("integer");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "EnFirstName", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantPersonalInfo#ApplicantPersonalInfo.EnFirstName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("EnFirstName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "EnLastName", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantPersonalInfo#ApplicantPersonalInfo.EnLastName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("EnLastName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FirstName", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantPersonalInfo#ApplicantPersonalInfo.FirstName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("FirstName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "LastName", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantPersonalInfo#ApplicantPersonalInfo.LastName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("LastName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "NationalCode", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantPersonalInfo#ApplicantPersonalInfo.NationalCode#NationalCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("NationalCode");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "PersonalImageFileId", "Student.Api.Domain.Admission.AdmissionRequest.ApplicantPersonalInfo#ApplicantPersonalInfo.PersonalImageFileId#FileId", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<Guid>("Value")
                                        .HasColumnType("uuid")
                                        .HasColumnName("PersonalImageFileId");
                                });

                            b1.HasDiscriminator<bool>("HasApplicantPersonalInfo").HasValue(true);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DiplomaInfo", "Student.Api.Domain.Admission.AdmissionRequest.DiplomaInfo#DiplomaInfo", b1 =>
                        {
                            b1.Property<decimal>("Average")
                                .HasColumnType("numeric");

                            b1.Property<string>("Field")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("GraduationYear")
                                .HasColumnType("integer");

                            b1.Property<bool>("HasDiplomaInfo")
                                .HasColumnType("boolean");

                            b1.HasDiscriminator<bool>("HasDiplomaInfo").HasValue(true);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EmergencyContact", "Student.Api.Domain.Admission.AdmissionRequest.EmergencyContact#EmergencyContact", b1 =>
                        {
                            b1.Property<bool>("HasEmergencyContact")
                                .HasColumnType("boolean");

                            b1.Property<string>("Relation")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FirstName", "Student.Api.Domain.Admission.AdmissionRequest.EmergencyContact#EmergencyContact.FirstName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("EmergencyContactFirstName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "LastName", "Student.Api.Domain.Admission.AdmissionRequest.EmergencyContact#EmergencyContact.LastName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("EmergencyContactLastName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Mobile", "Student.Api.Domain.Admission.AdmissionRequest.EmergencyContact#EmergencyContact.Mobile#MobileNumber", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(11)
                                        .HasColumnType("character varying(11)")
                                        .HasColumnName("EmergencyContactMobile");
                                });

                            b1.HasDiscriminator<bool>("HasEmergencyContact").HasValue(true);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EntranceInfo", "Student.Api.Domain.Admission.AdmissionRequest.EntranceInfo#EntranceInfo", b1 =>
                        {
                            b1.Property<int>("AdmissionMethod")
                                .HasColumnType("integer");

                            b1.Property<int>("AdmissionType")
                                .HasColumnType("integer");

                            b1.Property<int?>("EntranceExamRank")
                                .HasColumnType("integer");

                            b1.Property<double?>("EntranceScore")
                                .HasColumnType("double precision");

                            b1.Property<bool>("HasEntranceInfo")
                                .HasColumnType("boolean");

                            b1.Property<int>("Quota")
                                .HasColumnType("integer");

                            b1.HasDiscriminator<bool>("HasEntranceInfo").HasValue(true);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FatherInfo", "Student.Api.Domain.Admission.AdmissionRequest.FatherInfo#ParentInfo", b1 =>
                        {
                            b1.Property<bool>("HasFatherInfo")
                                .HasColumnType("boolean");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FirstName", "Student.Api.Domain.Admission.AdmissionRequest.FatherInfo#ParentInfo.FirstName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("FatherFirstName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "LastName", "Student.Api.Domain.Admission.AdmissionRequest.FatherInfo#ParentInfo.LastName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("FatherLastName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Mobile", "Student.Api.Domain.Admission.AdmissionRequest.FatherInfo#ParentInfo.Mobile#MobileNumber", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(11)
                                        .HasColumnType("character varying(11)")
                                        .HasColumnName("FatherMobile");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "NationalCode", "Student.Api.Domain.Admission.AdmissionRequest.FatherInfo#ParentInfo.NationalCode#NationalCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("FatherNationalCode");
                                });

                            b1.HasDiscriminator<bool>("HasFatherInfo").HasValue(true);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MotherInfo", "Student.Api.Domain.Admission.AdmissionRequest.MotherInfo#ParentInfo", b1 =>
                        {
                            b1.Property<bool>("HasMotherInfo")
                                .HasColumnType("boolean");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "FirstName", "Student.Api.Domain.Admission.AdmissionRequest.MotherInfo#ParentInfo.FirstName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("MotherFirstName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "LastName", "Student.Api.Domain.Admission.AdmissionRequest.MotherInfo#ParentInfo.LastName#Name", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("MotherLastName");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Mobile", "Student.Api.Domain.Admission.AdmissionRequest.MotherInfo#ParentInfo.Mobile#MobileNumber", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(11)
                                        .HasColumnType("character varying(11)")
                                        .HasColumnName("MotherMobile");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "NationalCode", "Student.Api.Domain.Admission.AdmissionRequest.MotherInfo#ParentInfo.NationalCode#NationalCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("MotherNationalCode");
                                });

                            b1.HasDiscriminator<bool>("HasMotherInfo").HasValue(true);
                        });

                    b.HasKey("Id");

                    b.HasIndex("RegistrationToken")
                        .IsUnique();

                    b.ToTable("AdmissionRequests", (string)null);
                });

            modelBuilder.Entity("Student.Api.Domain.Admission.AdmissionRequest", b =>
                {
                    b.OwnsMany("Student.Api.Domain.Admission.AdmissionAttachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AdmissionRequestId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("AdmissionRequestId");

                            b1.ToTable("AdmissionAttachments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AdmissionRequestId");

                            b1.OwnsOne("SharedKernel.Domain.Identifiers.FileId", "FileId", b2 =>
                                {
                                    b2.Property<Guid>("AdmissionAttachmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("Value")
                                        .HasColumnType("uuid")
                                        .HasColumnName("FileId");

                                    b2.HasKey("AdmissionAttachmentId");

                                    b2.ToTable("AdmissionAttachments");

                                    b2.WithOwner()
                                        .HasForeignKey("AdmissionAttachmentId");
                                });

                            b1.Navigation("FileId")
                                .IsRequired();
                        });

                    b.OwnsOne("Student.Api.Domain.Admission.ValueObjects.TrackingCode", "TrackingCode", b1 =>
                        {
                            b1.Property<Guid>("AdmissionRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("TrackingCode");

                            b1.HasKey("AdmissionRequestId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("AdmissionRequests");

                            b1.WithOwner()
                                .HasForeignKey("AdmissionRequestId");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("TrackingCode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
