// <auto-generated />
using System;
using System.Collections.Generic;
using File.Api.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace File.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FileDbContext))]
    [Migration("20260704141232_AddStoragePath")]
    partial class AddStoragePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("File.Api.Domain.File.File", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AttachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FileName", "File.Api.Domain.File.File.FileName#FileName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("FileName");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AttachedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("File.Api.Domain.File.File", b =>
                {
                    b.OwnsOne("File.Api.Domain.File.ValueObjects.FileHash", "Hash", b1 =>
                        {
                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Hash");

                            b1.HasKey("FileId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Files");

                            b1.WithOwner()
                                .HasForeignKey("FileId");
                        });

                    b.Navigation("Hash");
                });
#pragma warning restore 612, 618
        }
    }
}
