// <auto-generated />
using System;
using Academic.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Academic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AcademicDbContext))]
    partial class AcademicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Academic.Domain.Course.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PracticalCredits")
                        .HasColumnType("integer");

                    b.Property<int>("TheoreticalCredits")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId", "IsActive");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_courses_practical_credits", "\"PracticalCredits\" >= 0");

                            t.HasCheckConstraint("ck_courses_theoretical_credits", "\"TheoreticalCredits\" >= 0");

                            t.HasCheckConstraint("ck_courses_total_credits", "\"TheoreticalCredits\" + \"PracticalCredits\" > 0");
                        });
                });

            modelBuilder.Entity("Academic.Domain.Curriculum.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid");

                    b.Property<int>("MinimumRequiredCredits")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MajorId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 2");

                    b.HasIndex("MajorId", "Status");

                    b.ToTable("Curricula", null, t =>
                        {
                            t.HasCheckConstraint("ck_curricula_effective_dates", "\"EffectiveTo\" IS NULL OR \"EffectiveTo\" >= \"EffectiveFrom\"");

                            t.HasCheckConstraint("ck_curricula_minimum_required_credits", "\"MinimumRequiredCredits\" > 0");
                        });
                });

            modelBuilder.Entity("Academic.Domain.Major.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "IsActive");

                    b.ToTable("Majors", (string)null);
                });

            modelBuilder.Entity("Academic.Domain.Course.Course", b =>
                {
                    b.OwnsMany("Academic.Domain.Course.CoursePrerequisite", "Prerequisites", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("PrerequisiteCourseId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("PrerequisiteCourseId");

                            b1.HasIndex("CourseId", "PrerequisiteCourseId")
                                .IsUnique();

                            b1.ToTable("CoursePrerequisites", null, t =>
                                {
                                    t.HasCheckConstraint("ck_course_prerequisites_not_self", "\"CourseId\" <> \"PrerequisiteCourseId\"");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CourseId");

                            b1.HasOne("Academic.Domain.Course.Course", null)
                                .WithMany()
                                .HasForeignKey("PrerequisiteCourseId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("Academic.Domain.Curriculum.Curriculum", b =>
                {
                    b.HasOne("Academic.Domain.Major.Major", null)
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Academic.Domain.Curriculum.CurriculumCourse", "Courses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Category")
                                .HasColumnType("integer");

                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("CurriculumId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("DisplayOrder")
                                .HasColumnType("integer");

                            b1.Property<int>("RequirementType")
                                .HasColumnType("integer");

                            b1.Property<int>("SuggestedSemester")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("CourseId");

                            b1.HasIndex("CurriculumId", "CourseId")
                                .IsUnique();

                            b1.HasIndex("CurriculumId", "SuggestedSemester", "DisplayOrder");

                            b1.ToTable("CurriculumCourses", null, t =>
                                {
                                    t.HasCheckConstraint("ck_curriculum_courses_display_order", "\"DisplayOrder\" IS NULL OR \"DisplayOrder\" > 0");

                                    t.HasCheckConstraint("ck_curriculum_courses_suggested_semester", "\"SuggestedSemester\" > 0");
                                });

                            b1.HasOne("Academic.Domain.Course.Course", null)
                                .WithMany()
                                .HasForeignKey("CourseId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("CurriculumId");
                        });

                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
